name = "QuickVega"
uuid = "8cbdc466-600a-49fa-b107-91fd9d936351"
authors = ["David Anthoff <anthoff@berkeley.edu>", "Davi Barreira <davisbarreira@gmail.com>"]
version = "0.1.0"

[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
julia = "1"
